pfsimulator/parflow_lib/input_database.h
Pretty obvious, just a typo in which an:
```
#ifdef PROTECTION_HEADER
#define PROTETION
...
#endif
```
didnt' match.  (Note the Hypre and Silo issues were fixed when I went to the github repo instead of the svn one).
=> header protection in input_database did not match #ifdef to #define

test/crater2D_vangtable_spline.tcl, test/pftest.llnl.cab.msub, test/pftest.llnl.quartz.sbatch, test/pftest.tcl
The crater2d_vangtable_spline regression test was signalling a failure when pressure values near zero were showing significant digit differences.   Comparison was changed so that pressure value differences near absolute zero are ignored.
Closes #29
=> Crater2D regression test fix

CMakeLists.txt
Was using "." to get directory to install to root of installation prefix, CMake uses "/" appended to src directory name to prevent appending.   This avoids having a "/./" in path names.
=> Updated path for config install to be more consistent with CMake 

CMakeLists.txt, README-Spack.md, pfsimulator/parflow_exe/CMakeLists.txt
Fixed CMake NetCDF variable names
=> Use local Spack compile on MacOS.

pfsimulator/clm/clm.F90
Intel compiler failed to compile CLM due to incorrect ordering of parameter declarations.
Fixes #112
=> Fix declaration order of parameters.   

pfsimulator/clm/drv_readclmin.F90
CLM was reading ts value from drv_dlmin.dat file.   The ts was overriding timestep supplied by Parflow causing incorrect results.
=> Remove CLM ts as an input value.

pftools/printdatabox.c
Several functions in printdatabox.c appear to have small memory leaks. Several calls to malloc are missing an associated call to free. The variable DTd in several functions appears to be malloc'd and then assigned to a pre-existing allocated block of memory belonging to a Databox (which was already allocated).
In one case, DTd is freed after pointing to a block of memory owned by an existing Databox. This can create a double free error when attempting to call FreeDatabox on this Databox object. 
One other apparent issue that I just noticed (and didn't correct yet) is that DTf is allocated a much larger block of memory than it requires. The size should be NX*NY*NZ, not nxyzp*3.
=> Fixed some small memory leaks and one premature deallocation

pftools/printdatabox.c
Some memory allocations had an incorrect multiply by 3.   Likely cut-paste error.
Fixes #128
=> Fixed memory allocation sizes

docs/manuals/pftools.tex, pftools/pftools.c, test/LW_var_dz.tcl
Users had to manually set number of cells in Z for pfdist to work on 1D datasets.   Add flag to pfdist command to enable using the command without setting the key.
Fixes #142
=> Manual override flag (-nz) for layer numbers to pfdist command

pfsimulator/parflow_lib/grgeometry.c, pfsimulator/parflow_lib/kinsol_nonlin_solver.c, pfsimulator/parflow_lib/kinsol_pc.c, pfsimulator/parflow_lib/nl_function_eval.c, pfsimulator/parflow_lib/overlandflow_eval.c, pfsimulator/parflow_lib/overlandflow_eval_diffusive.c, pfsimulator/parflow_lib/parflow_proto.h, pfsimulator/parflow_lib/richards_jacobian_eval.c
Overland flow improvements require access to the previous pressure.   Added old pressure to the overland flow module interfaces.
Closes #152
=> Pass old pressure to overland flow evaluation methods

pfsimulator/clm/drv_clmini.F90
Two arrays are used to hold initial values; should be fixed size and not based on soil/lake levels from user input to avoid array bounds issues.
Fixes #151
=> Temporary initializer arrays should have fixed size 

pfsimulator/parflow_lib/overlandflow_eval_Kin.c, pfsimulator/parflow_lib/overlandflow_eval_diffusive.c
Fixed a bug in overland kinematic and overland diffusive that used the top function / macro incorrectly causing problems in 3D, orthogonal grid domains with a ground surface that is variable in z.
=> Bugfix itop

Dockerfile
Use MPI compilers for ParFlow build.
=> Docker build failing

Dockerfile, pfsimulator/amps/test/src/CMakeLists.txt
When the AMPS tests were introduced the CMake build rules didn't include MPI libraries which caused link failures in build.
Fixes #225
=> AMPS tests where not linking to MPI libraries

pfsimulator/amps/seq/amps.h, pfsimulator/amps/seq/amps_proto.h
The AMPS sequential layer had several bugs preventing it from compiling.  Tests are passing again with a sequential build.
Fixed #240
=> Fixed compilation issues in sequential amps layer

bin/valgrind.sup, pfsimulator/clm/drv_readvegpf.F90
GNU Fortran is generating a valgrind error in the write command.   This is known issue; added a valgrind suppression entry to silence.
MPI was generating a valgrind error in MPI_Init on quarts;  suppression was added to silence.
=> Bugfix Valgrind warnings

CMakeLists.txt
Would like to change the default build from using distributed IO to using sequential IO. In talking with @reedmaxwell, it was suggested that we make this change so new installations won't require explicitly setting the DPARFLOW_AMPS_SEQUENTIAL_IO=TRUE in every compilation.
=> make amps_sequential_io default TRUE

pfsimulator/amps/cuda/amps_init.c, pfsimulator/amps/mpi1/amps_init.c, pfsimulator/amps/oas3/amps_init.c, pfsimulator/amps/smpi/amps_init.c
Cleaned up declaration and initialization of AMPS_CPU_TICKS_PER_SEC.   Old initialization logic from deprecated platforms was declaring and initializing AMPS_CPU_TICKS_PER_SEC twice.
=> Cleaned up declaration and initialization of AMPS_CPU_TICKS_PER_SEC.

pfsimulator/parflow_lib/pf_cudaloops.h
Fix n_ival initialization bug which does not show up in ctests, but influences the results for a production case.
=> Fix CUDA patchloop ival initialization bug

pftools/python/parflow/tools/builders.py, pftools/python/parflow/tools/io.py, pftools/python/setup.py
1. The map and parameter file names are now pulled from the "drv_clmin.dat" file
before attempting to load them. Previously, they were assumed to be
"drv_vegm.dat" and "drv_vegp.dat".
2. When checking if the driver data is set, it now checks if land covers have
been set. Previously, it checked if the type of "Sand" was set, but that
is now always set since it defaults to "Constant".
3. Boolean type is now checked in the to_native_type() function.
This also bumps the version to 1.1.1.
=> Fix a few issues with pftools python CLM

.github/workflows/linux.yml, Dockerfile, Dockerfile_CUDA, cmake/recipes/centos-7-3, cmake/recipes/centos-7.3, cmake/recipes/ncar-cheyenne, cmake/recipes/nersc-cori, cmake/recipes/ubuntu-18.10-CUDA, docker/CMakeLists.txt, docker/dev/Dockerfile
I didn't find any official documentation that the url changed. But you will
notice that these urls no longer work:
https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2.tar.gz
https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2-bsd.tar.gz
And if you go to their [downloads page](https://wci.llnl.gov/simulation/computer-codes/silo), you will
see that the download links now point to these urls:
https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.10.2.tgz
https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.10.2-bsd.tgz
=> Update silo url

CONTRIBUTING.md, README.md, docs/software_plan.md, pftools/python/README.md
Fixed links from old mines mailman link to use new Google Groups list.
Fixes  #306
=> Updated links for ParFlow users email list to point to the new Google Group list

pfsimulator/parflow_lib/metadata.c
Do not print improper-metadata setup error messages
on every process at every timestep; print once at
initialization with a more complete description of
the problem.
=> Make errors less verbose and more descriptive.

pftools/python/parflow/tools/core.py, pftools/python/parflow/tools/database/core.py, pftools/python/requirements.txt, pftools/python/setup.py
Fix the following set of issues:
- Allow .value() to properly resolve keys in store
- Allow pfset to auto detect key prefix and store value in the proper container
- Add flexibility in property order when loading `from_definition`
- If CLM .dat file are not found, skip the generation of CLM keys
=> Py pftools misc fix

pftools/python/parflow/tools/io.py
`parflowio` has support for specifying DX/DY/DZ values of the `PFData` object, in addition to the array values themselves. I'm not sure what's special about DX/DY/DZ among all possible attributes of the run - none of the code in `parflowio` seems to be doing anything useful with this information other than keeping track of it, as far as I can tell. Nevertheless, support for these fields exist in the pfb file, so `parflowio` exposes getters/setters for these fields.
@reedmaxwell observed that the values reported by `parflowio` in some of our pfb files was incorrect. We are now modifying our code to set these correctly before writing out the pfb file. Addition of these optional parameters to `write_array`/`write_array_pfb` will allow us to use `pftools` directly for this purpose, and phase …
=> support for changing dx/dy/dz while writing pfb file

pftools/python/parflow/tools/core.py, pftools/python/parflow/tools/export.py
By default when CLM is used, we always try to export the .dat file
using the pf keys and pfb files. But if those were never defined,
such opperation would fail.
This fix try to guard against it.
=> Prevent eager CLM export when no clm keys have been defined

docs/pf-keys/tutorials/solid_files.rst, pftools/python/parflow/tools/builders.py
We've identified a need to use the `SolidFileBuilder` class to generate `.pfsol` files, but with a customized value of the `z-top` parameter (i.e. invoking the underlying `pfmask-to-pfsol` parflow utility with an additional `--z-top 1000` flag. This minor change should allow us to use the `SolidFileBuilder` class with any custom flags not exposed as explicit attributes in the class.
=> Support for extra parameters to pfmask-to-pfsol

.github/workflows/linux.yml
Ubuntu 16.04 support is being dropped from GitHub Actions, removing this virtual environment from the CI testing.
=> Remove Ubuntu 16.04 from CI

pfsimulator/amps/cuda/amps.h, pfsimulator/amps/cuda/amps_finalize.c, pfsimulator/amps/cuda/amps_init.c, pfsimulator/amps/cuda/amps_proto.h, pfsimulator/amps/cuda/amps_recv.c, pfsimulator/amps/cuda/amps_send.c, pfsimulator/amps/mpi1/amps.h, pfsimulator/amps/mpi1/amps_exchange.c, pfsimulator/amps/mpi1/amps_finalize.c, pfsimulator/amps/mpi1/amps_init.c, pfsimulator/amps/mpi1/amps_proto.h, pfsimulator/amps/mpi1/amps_recv.c, pfsimulator/amps/mpi1/amps_send.c, pfsimulator/amps/smpi/amps.h, pfsimulator/amps/smpi/amps_finalize.c, pfsimulator/amps/smpi/amps_init.c, pfsimulator/amps/smpi/amps_proto.h, pfsimulator/amps/smpi/amps_recv.c, pfsimulator/amps/smpi/amps_send.c
Enable use of a communicator other than MPI_COMM_WORLD for more general embedding.
Meet IDEAS Watersheds best practices policy.
=> Remove use of MPI_COMM_WORLD

pftools/python/parflow/tools/io.py, pftools/python/setup.py
This PR fixes a leftover reference to parflowio that wasn't removed in #365. It also makes the numba dependency optional as there are still some issues with installing on Mac M1 based machines.
=> Remove reference to parflowio, relax requirement on numba

pftools/python/parflow/tools/io.py, pftools/python/setup.py
The `_read_vegm` function in PFTools is inconsistent with parflow-python xy indexing. This fix swaps the indices so that the x index of the `vegm_array` correctly reflects the columns and y index reflects the rows.
=> Python PFTools vegm file reader fix

pftools/python/setup.py
I had to bump the PFTools version to `1.3.4` (version `1.3.3` was released incorrectly). This change now reflects the latest working version on pypi.
=> PFTools 1.3.4

CMakeLists.txt
Require Python 3.6 in CMake
fixes #376
=> Update Python version; using features from 3.6

pfsimulator/parflow_lib/input_database.c, pfsimulator/parflow_lib/input_database.h
the maximum input database value length was increased from 4097 to 65536. A bounds check is performed that emits a helpful error message when a database value is too big.
4097 to 65536 seems like a big increase, but IDB_MAX_VALUE_LEN is only used once as a buffer size to read database entries. The char pointers are then null-terminated and passed to IDB_NewEntry, where strdup mallocs an appropriate string size. The strings are still freed in the same place.
1. All tests pass on my personal laptop configured with Hypre and CLM, except for those that exceed my available processors.
2. A modified copy of impes.simple.tcl was configured with a key of size 65535. It ran without segfaulting.
3. A modified copy of impes.simple.tcl was configured with a key of size 65536. It produced the desired …
=> Increased input database maximum value size from 4097 to 65536

pftools/python/CHANGELOG.md, pftools/python/parflow/tools/io.py, pftools/python/parflow/tools/pf_backend.py, pftools/python/parflow/tools/util.py, pftools/python/setup.py
- Fix a bug on xarray indexing which require squeezing out multiple dimensions
- Add the ability to give keys to the pf.read_pfb function for subsetting
- Performance improvement with xarray by removing dask delayed call, which
caused threadlocks. Lazy loading is implemented natively now with changes to
the indexing methods.
- Fixes #388
=> Minor improvements/bugfix for python IO

pfsimulator/third_party/cub/util_namespace.cuh
This PR fixes the compile error when using CUDA 11.5 or later. 
```
In file included from /opt/software/CUDA/11.5/targets/x86_64-linux/include/thrust/system/cuda/config.h:73,
from /opt/software/CUDA/11.5/targets/x86_64-linux/include/thrust/system/cuda/detail/execution_policy.h:35,
from /opt/software/CUDA/11.5/targets/x86_64-linux/include/thrust/iterator/detail/device_system_tag.h:23,
from /opt/software/CUDA/11.5/targets/x86_64-linux/include/thrust/iterator/detail/iterator_facade_category.h:22,
from /opt/software/CUDA/11.5/targets/x86_64-linux/include/thrust/iterator/iterator_facade.h:37,
from /home/user/parflow/pfsimulator/parflow_lib/../third_party/cub/device/../iterator/arg_index_input_iterator.cuh:48,
from /home/user/parflow/pfsimulator/parflow_lib/../third_party/cub/device/device_reduc …
```
=> Starting from CUB 1.14, CUB_NS_QUALIFIER macro must be specified

pftools/python/parflow/tools/io.py
This addresses https://github.com/parflow/parflow/issues/402 
It adds the `read_subgrid_info` method to the `ParflowBinaryReader` class, which directly reads the subgrid header from file, rather than calculating that info using _nx_, _ny_, _nz_, _p_, _q_ and _r_. This is useful when reading velocity files. For example, since velx files report values at cell faces in the _x_ direction, if _p_ > 1 in the process topology, each subgrid includes one extra row/column in the _x_ direction. 
To fix the use case in https://github.com/parflow/parflow/issues/402, use `read_sginfo=True` when reading velocity files:
```python
from parflow import read_pfb
velx = read_pfb('default_richards.out.velx.00001.pfb',
read_sginfo=True)
print(velx.min(), velx.max())
```
=> Python PFTools, read subgrid info from file

docs/user_manual/models.rst
Based on the [PFtools water balance formulation](https://github.com/parflow/parflow/blob/master/pftools/water_balance.c), it seems that (\psi) is repeated in the second half of Eq. 4.35. Also notice that ∆𝑥, ∆𝑦, and ∆z are not defined in Section 4 (MODEL EQUATIONS).
=> Error in Eq. 4.35 - Subsurface storage

.github/workflows/linux.yml, misc/build_scripts/build.oasis3.ubuntu20.04
Unify NetCDF usage, the apt package NetCDF is not built with options needed by the PF writer.   Use a consistent NetCDF build for PF writer and OASIS3 builds to avoid conflicts.
=> Netcdf clean

docs/user_manual/keys.rst
Something similar should be done for the remaining input files, so model users can easily understand if a 2D or 3D file is expected as input.
=> Specify that slopex and slopey files are expected to be 2D pfbs

docs/user_manual/keys.rst
Changes apply to:
- Boundary Conditions: Overland Flow
- Permeability tensors
- Porosity
- dzScale 
- Mannings
- VanGenuchten
- Initial Conditions: Pressure
- Initial Conditions: Phase Concentrations
NOTE: Flow barrier files, PressureFile, and FluxFile are pending as I am not sure if they are supposed to be 3D  PFB files. If yes, please confirm and I will make the respective edits.
=> Specify that certain input files are 2D or 3D pfb files

docs/user_manual/keys.rst
There is a small typo in naming some pf-keys:
`pfset Geom.domain.Perm.TensorByFileX` -->  `pfset Geom.domain.Perm.TensorFileX`   
`pfset Geom.domain.Perm.TensorByFileY` -->  `pfset Geom.domain.Perm.TensorFileY`   
`pfset Geom.domain.Perm.TensorByFileZ` -->  `pfset Geom.domain.Perm.TensorFileZ`   
Not sure if the same applies to python syntax as well, as Im not using this.
=> Typo in keys.rst at PermTensor

docs/user_manual/keys.rst
Typo in Haverkamp saturation formula: alpha replaced with A.
Correct formula from:
Haverkamp, R. and Vauclin, M. (1981), A Comparative Study of Three Forms of the Richard Equation Used for Predicting One-Dimensional Infiltration in Unsaturated Soil. Soil Science Society of America Journal, 45: 13-20. https://doi.org/10.2136/sssaj1981.03615995004500010003x
=> Error in Haverkamp saturation formula

docs/user_manual/keys.rst
Top flux boundary conditions (e.g., OverlandFlow, SeepageFace) and EvapTrans files do not follow the same sign convention:
- Top flux boundary conditions require a sign flip (i.e., outgoing fluxes are positive) ~ Evidence: [default_overland.tcl](https://github.com/parflow/parflow/blob/master/test/tcl/default_overland.tclL308))
- EvapTrans files do not require a sign flip (i.e., outgoing fluxes are negative) ~ Evidence: [overland_flux.tcl](https://github.com/parflow/parflow/blob/master/test/tcl/overland_flux.tcl#L322)
I specified this information in the respective keys. I also specified that EvapTrans files are expected to be ParFlow 3D binary files.
=> Sign convention for top flux boundary conditions and EvapTrans files

RELEASE-NOTES.md, test/python/CMakeLists.txt, test/python/clm/CMakeLists.txt, test/python/new_features/CMakeLists.txt, test/python/new_features/clm/CMakeLists.txt
Added guards to check if optional packages are installed when running python regression tests
The following tests should not run when HYPRE is missing: 
py_prefix_naming
py_serial_runs
py_simple-mask
py_washita
py_washita_clm_keys
py_clm_reuse
py_clm, py_clm_varDZ
py_clm.jac
py_clm_forc_veg
py_clm_4levels
py_clm_slope
The following tests should not run when CLM is missing: 
py_washita
py_washita_clm_keys 
The following tests should not run when SILO is missing: 
py_default_overland.pfmg_octree.jac
py_clm
py_clm_varDZ
py_clm.jac
py_clm_forc_veg
py_clm_4levels
=> Python tests optional dependencies fixes #367

pftools/CMakeLists.txt, pftools/pfmask-to-pfsol.cpp
Compiling parflow with the Intel-OneAPI compiler throws the following warning:
pfmask-to-pfsol.cpp:444:6: warning: comparison with NaN always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
if(isnan(dx))
There are a few more warnings like that coming from the pfmask-to-pfsol NaN checks.
Basically, NaN checks are ignored in fast floating-point mode, which leads to bugs in the pfmask-to-pfsol script and erroneous solidfiles being produced.
This PR fixes this by replacing the NaN sentinel with FLT_MIN.
Also, a typo on line 406 of pfmask-to-pfsol is corrected.
=> Pfmask to pfsol compile fix

.github/workflows/linux.yml, pfsimulator/amps/mpi1/amps_gpupacking.cpp, pfsimulator/parflow_lib/pf_kokkos.cpp, pfsimulator/parflow_lib/pf_kokkosloops.h
This PR refactors deprecated code in for compatibility with Kokkos starting from version v4.0, and resolves a bug related to multiple finalize calls in the Kokkos HIP execution space.
However, further refactoring is required for the Kokkos backend code to remove deprecated code in Kokkos v3.x. Meanwhile, the following CMake configuration can be used to enable support for deprecated code when compiling Kokkos:
`-DKokkos_ENABLE_DEPRECATED_CODE_3=ON`
I have thoroughly tested these changes with various run configurations and variants of the testcase [clayL.tcl](https://github.com/parflow/parflow/blob/master/test/tcl/clayL.tcl) on
- [JURECA (AMD MI250 GPUs)](https://apps.fz-juelich.de/jsc/hps/jureca/evaluation-platform-overview.html), and
- [LUMI (AMD MI250X GPUs based on the 2nd Gen AMD CDNA …
=> Compatibility Refactoring for Kokkos starting from v4.0 and a bug Fix for Kokkos (HIP) execution space

pftools/python/parflow/tools/core.py, pftools/python/parflow/tools/io.py, test/python/new_features/CMakeLists.txt, test/python/new_features/pfb_reader.py
run.dist() does not re-distribute well files that have been already been distributed in a way that p, q, r do not exactly divide NX, NY, NZ. The problem lies in trying to "estimate" p, q, r when reading those distributed files in with the ParflowBinaryReader.
This pull request removes the precomputation option (which cannot work if we allow distributing grids unevenly), and adds explicit calculation for p, q, r in the read_subgrid_info. Also, a test for ParflowBinaryReader is added, which distributes and redistributes a pfb file. That test fails with the previous implementation.
=> Fix bug in run.dist()

bin/pfformat
If parflow is built with a python environment, those package C files should not be subject to uncrustify checks.
=> Remove C files within py-env from uncrustify check

.github/workflows/linux.yml
Remove third party action that was broken.   The awalsh128/cache-apt-pkgs-action package looks to be unsupported and does not work with recent GitHub changes.
=> Update artifact actions

CMakeLists.txt, pfsimulator/amps/CMakeLists.txt, pfsimulator/amps/mpi1/CMakeLists.cmake, pfsimulator/amps/test/src/CMakeLists.txt, pfsimulator/amps/test/src/test13.c, pfsimulator/parflow_exe/CMakeLists.txt, pfsimulator/parflow_lib/CMakeLists.txt, pfsimulator/parflow_lib/f2c.h, pfsimulator/parflow_lib/fgetopt.h, pfsimulator/parflow_lib/metadata.h, pfsimulator/parflow_lib/n_vector.c, pfsimulator/parflow_lib/n_vector.h, pfsimulator/parflow_lib/parflow_proto.h, pfsimulator/parflow_lib/ratqr.c, pfsimulator/parflow_lib/vector_utilities.c, pfsimulator/parflow_lib/write_clm_netcdf.c, pfsimulator/parflow_lib/write_parflow_netcdf.c
CMake flag added to enable compiling ParFlow as C++.
Minor changes to fix minor C++ compatibility issues.
=> Add flag to enable building ParFlow using C++ compiler 

.github/workflows/linux.yml
This PR introduces two updates:
1. PDI installation simplification: PDI is now installed directly into PARFLOW_DEP_DIR, aligning with other dependencies and reducing complexity in setup.
2.  Fix for CUDA atomicAdd(double) build error: Added CMAKE_CUDA_ARCHITECTURES=60;70;75;80 to linux.yml to ensure support for double-precision atomicAdd, which requires compute capability ≥ 6.0.
These changes were tested on my fork and passed all CI jobs, including the CUDA build.
=> Simplify PDI installation and fix CUDA atomicAdd support in CI

.github/workflows/self_hosted.yml
Self host runner only works from within the ParFlow project, skip the test when run from forks to save time waiting for test to time-out.
=> Limit where self hosted runner is used

bin/pfformat
Add exit codes for pfformat when uncrustify is not found or correct version.
Fixes #623
=> CI Check style check incorrectly reports success

pfsimulator/amps/mpi1/amps_gpupacking.cpp, pfsimulator/parflow_lib/pf_kokkos.cpp
This PR refactors `KokkosMemSet` operations by replacing manual zero-initialization via `parallel_for `with a more efficient and portable `Kokkos::deep_copy` on unmanaged memory views. This improves overall Kokkos performance, simplifies logic, and aligns with modern Kokkos best practices.
**Summary of Changes:**
- Replaced loop-based based zeroing with `Kokkos::deep_copy` using unmanaged views.
- Scoped synchronization instead of a global `Kokkos::fence()`.
- Removed alignment-based branching logic, simplifying code and improving readability.
**Performance Comparison (vs Native CUDA on NVIDIA A100):**
- Up to ~38% reduction in solve time compared to the previous loop based implementation.
- Performance gap with native CUDA closes up to ~95%.
=> Refactor Zero-Initialization MemSet for Improved Kokkos Performance

.github/workflows/linux.yml, .github/workflows/macos.yml
Previous method of using variable to force rebuilds was manual and caused issues.   Forks can not see the cache variable which also can cause problems.   Changed to use hash of the workflow files to trigger cache builds.   This is conservative and will cause some unnecessary builds but workflow changes are relatively infrequent.
=> Use file hashes to trigger Github Actions cache builds

.github/workflows/linux.yml
Style check workflow was installing uncrustify in a non-cached directory.   Move to the cache.
=> Fix style check workflow

pftools/python/pyproject.toml
With the new pftools build, the dependencies like numpy and pandas weren't pulled automatically. This PR fixes this. We also need to publish a new pftools version on PyPI so that this is available to users.
=> Fix dependencies in pyproject.toml

docs/user_manual/keys.rst
fixes documentation error in CLM Dump Interval, will fix Python key bounds check next which is also in error
=> Update CLMDumpInterval description in keys.rst

docs/user_manual/keys.rst, pf-keys/definitions/solver.yaml, pfsimulator/clm/clm.F90, pfsimulator/parflow_lib/CMakeLists.txt, pfsimulator/parflow_lib/compute_top_and_bottom.c, pfsimulator/parflow_lib/parflow_proto.h, pfsimulator/parflow_lib/parflow_proto_f.h, pfsimulator/parflow_lib/problem.c, pfsimulator/parflow_lib/problem.h, pfsimulator/parflow_lib/solver_richards.c
In this Pull Request is implemented the computation of a vector storing the index values for the bottom of the domain.
- This PR is meant to pave the road for an upcoming bottom BC feature.
- In addition, this PR addresses Issue #588, where the indices for the top and bottom of the domain are passed onto CLM, instead of having CLM compute it again.
=> Compute top and bottom of the domain

test/python/CMakeLists.txt, test/python/default_overland.pfmg_octree.jac.py, test/python/default_single.py, test/python/default_single_read_porosity.py, test/python/reservoir_mpi_test.py
This PR addresses Issue #643:
- Some python tests were running with 2D or 3D topologies while setting (P, Q, R) = (1, 1, 1) in the input script;
- The python tests where this happened (including `default_single.py`) were identified;
- This PR fixes the test scripts and ensures they are running the correct topologies.
=> Fix process topology of python tests
