acmacros/casc_hypre.m4
pfsimulator/configure

hypre has a dependency on MPI so include MPI libs in configure test for working hypre library

hypre dependency on MPI in configure

---

.travis.yml

Adding CLM to the TravisCI testing and doing some testing of workflow.

Added CLM to TravisCI regression testing

---

.travis.yml
test/Makefile
test/clm/Makefile

Added parallel tests to TravisCI.
Added timing output to regression tests.

Adding parallel tests to TravisCI regression tests

---

pfsimulator/parflow_lib/nl_function_eval.c

wrong sep calculation for u_new in dirichletBC(z-dir)  and typo in fluxBC(z-dir , -1-dir)
-please delete <nl_function_bugfix> branch after merge.

fix in nl_function_eval 

---

pftools/docs/software_plan.md

This pull request adds a single document, the software productivity and sustainability plan for ParFlow.

Software Plan

---

pfsimulator/parflow_lib/solver_richards.c

Velocity vectors allocated twice and not deallocated after use.

fix memory leaks

---

pftools/docs/amps_manual/Makefile.in
pftools/docs/dev_manual/Makefile.in
pftools/docs/usr_manual/Makefile.in

Fixes manual builds when doing in source tree configures.
Fixes #21

Manual build

---

test/Makefile
test/clm/Makefile

Remove time command for better portability to MacOS.

---

pfsimulator/parflow_lib/write_parflow_netcdf.c

Hi Steve,
I forgot to remove a print statement. This would create too many log entries. It would be great if we can merge it back to master.

Removed print statement

---

CMakeLists.txt
cmake/parflow_config.h.in
pfsimulator/parflow_exe/CMakeLists.txt
pfsimulator/parflow_lib/CMakeLists.txt

CMake seems to be case sensitive ;)

Fix typo in CMakeLists.txt

---

pfsimulator/clm/drv_pout.F90
pfsimulator/clm/drv_restart.F90
pfsimulator/parflow_exe/main.c
pfsimulator/parflow_exe/parflow.c
pfsimulator/parflow_lib/kinsol_nonlin_solver.c

Remove debugging prints
Closes #75

Only do status prints from rank 0

---

pftools/pftools.c
pftools/pftools.h

pfsetgrid failed on second execution due to bug in use of strtok. 

---

cmake/recipes/ubuntu-18.10

Build instructions updated for Ubuntu 18.10.

Added recipe for Ubuntu 18.10

---

pfsimulator/parflow_exe/main.c

Fix argument processing for SAMRAI restart

Remove debug argument print from output.

---

README.md
docs/manuals/CMakeLists.txt

Added user manual link and build instructions to readme.
Add installation of manuals

Add documentation to install

---

pfsimulator/parflow_lib/pf_pfmg_octree.c
test/CMakeLists.txt
test/default_overland.pfmg_octree.fulljac.tcl

Added test case using PFMGOctree and FullJacobian.
Fixes #131

Fixed bug in PFMGOctree indices for non-symmetric matrix.

---

pfsimulator/parflow_exe/main.c
pfsimulator/parflow_lib/grgeom_octree.c
pfsimulator/parflow_lib/timing.c
test/Makefile
test/clm/Makefile
test/clm/clm-reuse/.gitignore
test/timing/timing-pfmg-octree.tcl
test/washita/tcl_scripts/.gitignore

Added a CSV file with timing output.   Should make it easier to write Python scripts for performance studies.

Machine parsable timing output

---

pftools/pfmask-to-pfsol.cpp

Fixed missing include

---

docs/manuals/files.tex

Fixed CLM single binary documentation

---

docs/manuals/pftools.tex
pftools/pftools.c
test/LW_var_dz.tcl

1. Adding manual override flag (-nz) for layer numbers to pfdist command and, 2. Updating manual page, and 3. Added key to LW_var_dz.tcl test case to verify

Updates to pfdist

---

RELEASE-NOTES.md
test/LW_var_dz.tcl
test/LW_var_dz_spinup.tcl
test/clm/clm_forc_veg.tcl
test/washita/tcl_scripts/LW_NetCDF_Test.tcl
test/washita/tcl_scripts/LW_Test.tcl

Update release notes with info on pfdist -nz addition.

Use new -nz option for pfdist of 1D files

---

pfsimulator/parflow_lib/clustering.c

Fixed use of min when max is needed.

---

CONTRIBUTING.md

Added additional notes to contributing documentation.

Contributing documentation update

---

Dockerfile

Compile HDF; was not in CentOS package system.
Added NetCDF support.

Docker PF I/O options added to image

---

CMakeLists.txt
cmake/recipes/nersc-cori

Updated Cori recipe script and minor tweaks for to compile on Cori.

Cori configure update

---

bin/parflow-docker-test
docker-compose.test.yml

Added docker test script to run simple example after docker images are built.

Docker test script

---

README.md

Added link to overview paper to README.md.

Added overview paper reference

---

.travis.yml
Dockerfile
Dockerfile_CUDA

Getting dependencies in line with XSDK versions.

Update HYPRE package to current XSDK 0.5 version

---

pfsimulator/clm/infnan.F90

Tested build using GNU 10.2.0 compilers.
Fixes #256

Fixed compilation error with newer GFortran compilers

---

.travis.yml
test/python/silo/CMakeLists.txt

Added the new Python tests to TravisCI

Added testing of Python interface to TravisCI

---

.github/workflows/linux.yml
pfsimulator/parflow_lib/geometry.c

Adding new CI Testing using GitHub Actions since TravisCI has more complicated licensing.

Adding GitHub Actions for doing CI Testing

---

pftools/python/parflow/tools/core.py
pftools/python/parflow/tools/io.py
pftools/python/setup.py

Add data accessor

---

.github/workflows/linux.yml

Fixed regression test package updating.

Ubuntu 20 fix

---

pftools/parflow.tcl
pftools/pftformat.tcl
pftools/pkgIndex.tcl

Add missing TCL file with print commands to TCL package.
Update help information with new command names.
Fixes #311

Fixed documentation and include additional TCL file

---

CONTRIBUTORS.md
SPONSORS.md

Adding a SPONSORS.md file for recording funding agents supporting ParFlow development.
Fixes #314

Add a sponsors file

---

pftools/README.md
pftools/pfmask-to-pfsol.cpp
pftools/test/CMakeLists.txt

Top/bottom argument names were swapped.
Fixes #322

Fixed bug in argument naming

---

pfsimulator/parflow_lib/advect.F
pfsimulator/parflow_lib/sadvect.F

Change variable name to avoid conflict with reserved keyword stop

---

cmake/recipes/nersc-cori
test/hpc/submit.nersc.cori.sbatch

Updating for NERSC Cori building recipe and testing changes.

NERSC Cori updates

---

cmake/recipes/nersc-cori

Updating Cori recipe to avoid re-downloading tar files if they exist.

Minor update to NERSC Cori recipe

---

pftools/python/setup.py

Minor bugfix was needed in Python pftools for parsing versions, need to push this to pipy.

New version of pftools to push to pipy for Parflow v3.10.0

---

.github/workflows/linux.yml

Updating NVidia CUDA repository keys due to rotation as documented here:
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772

CUDA Linux Repository Key Rotation

---

docs/user_manual/keys.rst

Based on http://parflow.blogspot.com/2015/08/spinning-up-watershed-model.html

Correct formula in OverlandSpinupDampPX description

---

.github/workflows/linux.yml

Update hypre version used in CI suite.

Update hypre to 2.26.0

---

.github/workflows/linux.yml
CMakeLists.txt
Dockerfile
README.md
bin/pfrun

Add capability to run both Python and TCL based PF input files to the Docker image.
Update the hypre, silo, and netcdf dependencies used in the testing suite to more current versions.
Update the OS images used in the testing suite to more recent versions of Ubuntu.
Change base OS used in the Docker image to Ubuntu, update dependencies to match test suite.

Dependencies and Docker update

---

.github/workflows/linux.yml

GitHub Actions cache updated to V3

---

.github/workflows/linux.yml
bin/install-cuda.sh
install-cuda.sh

Update deprecated CUDA builds from Ubuntu 18.04 builds to 22.04.

Update CUDA test builds to Ubuntu 22.04

---

docs/manuals/release_process.tex

Add podman instructions for building images and pushing to dockerhub.

Release notes update

---

CMakeLists.txt
docker-compose.test.yml
pfsimulator/CMakeLists.txt

Update build to enable CLM only build

---

.github/workflows/linux.yml

OASIS testing using commit that does not exist

---

docs/user_manual/files.rst

qflx_tran_veg_ij was missing in the text

files_em.rst

---

test/python/default_single_read_porosity.py

Test was not actually using PFBFile option.

Fix Python porosity file read test

---

pfsimulator/parflow_lib/read_parflow_netcdf.c
pfsimulator/parflow_lib/timing.c
pfsimulator/parflow_lib/timing.h
pfsimulator/parflow_lib/write_parflow_netcdf.c

Adds timing information for Netcdf file I/O.

Netcdf timing

---

.github/workflows/linux.yml

Replace Ubuntu 20.04 with 24.04 in CI GitHub Actions

---

README.md

Clarifications and fixes to README

---

pfsimulator/parflow_lib/solver_richards.c

Move mask printing outside of initial_conditions flag check

---

.github/workflows/linux.yml

Update a few more tests to Ubuntu 24.04 from 22.04.
Add a few comments on CI strategy.

Minor ci updates

---

.github/workflows/linux.yml
.github/workflows/self_hosted.yml

Specify explicit versions for dependencies in CI workflows.

Specify explicit versions for dependencies in CI
